name: Scrapy Workflow

on:
  schedule:
    - cron: "0 17 * * *" # Run the workflow every day at 5 PM
  workflow_dispatch: # Enable manual trigger

jobs:
  run_spiders:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3 # Update to v3 which uses Node.js 20

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install playwright
          pip install scrapy-playwright

      - name: Run run_spiders.py
        run: |
          python run_spiders.py

      - name: Configure Git
        run: |
          git config user.name "githubactions"
          git config user.email "subheshjoshi@yahoo.com"

      - name: Commit and Push Changes
        run: |
          git add .
          git commit -m "Update data from Scrapy spiders"
          git push
